# Loads default set of integrations. Do not remove.
default_config:
 
# Text to speech
tts:
  - platform: google_translate

# automation: !include automations.yaml
# script: !include scripts.yaml
# scene: !include scenes.yaml

stream:
  ll_hls: true
  part_duration: 0.75
  segment_duration: 6

image_processing:
  - platform: sharpai
    source:
      - entity_id: camera.10_4_7_246
    scan_interval: 1
logger:
  default: critical
  logs:
    homeassistant.components.image_processing: info
    homeassistant.components.sharpai: info